# Generated by Django 5.2.8 on 2025-11-27 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם התוספת')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='מחיר תוספת')),
                ('pricing_type', models.CharField(choices=[('fixed', 'קבוע להזמנה'), ('per_person', 'לפי סועד')], default='fixed', max_length=20, verbose_name='סוג תמחור')),
                ('is_included', models.BooleanField(default=False, verbose_name='כלול כברירת מחדל בחבילה')),
                ('is_active', models.BooleanField(default=True, verbose_name='זמינה להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'תוספת בחבילה',
                'verbose_name_plural': 'תוספות בחבילות',
                'ordering': ['package', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='שם קטגוריית תוספת')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור כללי')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעילה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'קטגוריית תוספת',
                'verbose_name_plural': 'קטגוריות תוספות',
                'ordering': ['name'],
            },
        ),
    ]
