# Generated by Django 5.2.8 on 2025-11-27 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג (1-5)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='כותרת (אופציונלי)')),
                ('comment', models.TextField(blank=True, verbose_name='תוכן החוות דעת')),
                ('is_public', models.BooleanField(default=True, verbose_name='מוצג לכולם')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='הזמנה')),
            ],
            options={
                'verbose_name': 'חוות דעת',
                'verbose_name_plural': 'חוות דעת',
                'ordering': ['-created_at'],
            },
        ),
    ]
