# Generated by Django 5.2.8 on 2025-11-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(verbose_name='מספר סועדים')),
                ('status', models.CharField(choices=[('new', 'חדש'), ('processing', 'בתהליך'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='new', max_length=50, verbose_name='סטטוס הזמנה')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום כולל')),
                ('note', models.TextField(blank=True, null=True, verbose_name='הערות להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר יחידה בזמן ההזמנה')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום כולל לתוספת')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'תוספת בהזמנה',
                'verbose_name_plural': 'תוספות בהזמנה',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='מנה משודרגת')),
                ('extra_price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='תוספת מחיר למנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'פריט הזמנה',
                'verbose_name_plural': 'פריטי הזמנה',
            },
        ),
    ]
