# Generated by Django 5.2.8 on 2025-11-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('packages', '0001_initial'),
        ('products', '0002_remove_product_base_price_per_person'),
        ('vendors', '0002_alter_vendorprofile_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='מנה משודרגת'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guests_count',
            field=models.PositiveIntegerField(verbose_name='מספר סועדים'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='הערות להזמנה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='packages.package', verbose_name='חבילה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'חדש'), ('processing', 'בתהליך'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='new', max_length=50, verbose_name='סטטוס הזמנה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום כולל'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='לקוח'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendorprofile', verbose_name='ספק'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='תוספת מחיר למנה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='הזמנה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='package_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='packages.packagecategory', verbose_name='קטגוריה בחבילה'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='מוצר'),
        ),
    ]
