# Generated by Django 5.2.8 on 2025-11-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
        ('orders', '0002_remove_orderitem_price_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר יחידה בזמן ההזמנה')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום כולל לתוספת')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_addons', to='addons.addon', verbose_name='תוספת')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.order', verbose_name='הזמנה')),
            ],
            options={
                'verbose_name': 'תוספת בהזמנה',
                'verbose_name_plural': 'תוספות בהזמנה',
            },
        ),
    ]
