# Generated by Django 5.2.8 on 2025-11-27 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='שם העסק')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור העסק')),
                ('kashrut_level', models.CharField(blank=True, max_length=100, null=True, verbose_name=' כשרות')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='כתובת העסק')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/', verbose_name='תמונה/לוגו')),
                ('is_active', models.BooleanField(default=False, verbose_name='פעיל במערכת')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'פרופיל ספק',
                'verbose_name_plural': 'פרופילי ספקים',
                'ordering': ['-created_at'],
            },
        ),
    ]
