# Generated by Django 5.2.8 on 2025-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='פעיל במערכת'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='kashrut_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' כשרות'),
        ),
    ]
