# Generated by Django 5.2.8 on 2025-11-27 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם החבילה')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור החבילה')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='מחיר למנה')),
                ('min_guests', models.PositiveIntegerField(default=1, verbose_name='מספר סועדים מינימלי')),
                ('max_guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='מספר סועדים מקסימלי')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='תמונה מייצגת')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעילה להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'חבילה',
                'verbose_name_plural': 'חבילות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='שם הקטגוריה')),
                ('note', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('min_select', models.PositiveIntegerField(default=0, verbose_name='מינימום לבחירה')),
                ('max_select', models.PositiveIntegerField(blank=True, null=True, verbose_name='מקסימום לבחירה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעילה להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'קטגוריה בחבילה',
                'verbose_name_plural': 'קטגוריות בחבילות',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='מנה משודרגת')),
                ('extra_price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='תוספת מחיר למנה')),
                ('is_active', models.BooleanField(default=True, verbose_name='זמין להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'פריט בחבילת קטגוריה',
                'verbose_name_plural': 'פריטים בחבילת קטגוריה',
                'ordering': ['id'],
            },
        ),
    ]
