# Generated by Django 5.2.8 on 2025-11-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם החבילה')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר למנה')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'חבילה',
                'verbose_name_plural': 'חבילות',
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם קטגוריה')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='packages.package')),
            ],
            options={
                'verbose_name': 'קטגוריה בחבילה',
                'verbose_name_plural': 'קטגוריות בחבילות',
            },
        ),
    ]
