# Generated by Django 5.2.8 on 2025-11-20 22:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('products', '0002_remove_product_base_price_per_person'),
        ('vendors', '0002_alter_vendorprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'חבילה', 'verbose_name_plural': 'חבילות'},
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'ordering': ['id'], 'verbose_name': 'קטגוריה בחבילה', 'verbose_name_plural': 'קטגוריות בחבילות'},
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='תמונה מייצגת'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_guests',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='מספר סועדים מקסימלי'),
        ),
        migrations.AddField(
            model_name='package',
            name='min_guests',
            field=models.PositiveIntegerField(default=1, verbose_name='מספר סועדים מינימלי'),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='תאריך יצירה'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='פעילה להזמנה'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='max_select',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='מקסימום לבחירה'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='min_select',
            field=models.PositiveIntegerField(default=0, verbose_name='מינימום לבחירה'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='הערות'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='תיאור החבילה'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='פעילה להזמנה'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=150, verbose_name='שם החבילה'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='מחיר למנה'),
        ),
        migrations.AlterField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='vendors.vendorprofile', verbose_name='ספק'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='שם הקטגוריה'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='packages.package', verbose_name='חבילה'),
        ),
        migrations.AlterUniqueTogether(
            name='packagecategory',
            unique_together={('package', 'name')},
        ),
        migrations.CreateModel(
            name='PackageCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='מנה משודרגת')),
                ('extra_price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='תוספת מחיר למנה')),
                ('is_active', models.BooleanField(default=True, verbose_name='זמין להזמנה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.packagecategory', verbose_name='קטגוריה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='products.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'פריט בחבילת קטגוריה',
                'verbose_name_plural': 'פריטים בחבילת קטגוריה',
                'ordering': ['id'],
                'unique_together': {('package_category', 'product')},
            },
        ),
    ]
