# Generated by Django 5.2.8 on 2025-11-11 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='שם המוצר')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור המוצר')),
                ('category', models.CharField(blank=True, help_text='למשל: סלטים, מנות עיקריות, קינוחים', max_length=100, null=True, verbose_name='קטגוריה')),
                ('base_price_per_person', models.DecimalField(decimal_places=2, help_text='מחיר בסיסי למנה בהרכבה אישית (לא רלוונטי לחבילות מוכנות)', max_digits=10, verbose_name='מחיר למנה')),
                ('is_available', models.BooleanField(default=True, verbose_name='זמין להזמנה')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='תמונת מוצר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendorprofile', verbose_name='ספק')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_available'], name='products_pr_vendor__971b02_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx')],
            },
        ),
    ]
