# Generated by Django 5.2.8 on 2025-11-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='שם המוצר')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור המוצר')),
                ('category', models.CharField(blank=True, help_text='למשל: סלטים, מנות עיקריות, קינוחים', max_length=100, null=True, verbose_name='קטגוריה')),
                ('is_available', models.BooleanField(default=True, verbose_name='זמין להזמנה')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='תמונת מוצר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ['-created_at'],
            },
        ),
    ]
