# Generated by Django 5.2.8 on 2025-11-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price_per_person',
        ),
    ]
